import type { TemplateProps, DesignToken } from "@/components/templates/types";

export interface ShowcasePreset {
  id: string;
  name: string;
  description: string;
  token: DesignToken;
}

export const SHOWCASE_PRESETS: ShowcasePreset[] = [
  {
    id: "modern-tech",
    name: "Modern Tech (Indigo)",
    description: "SaaS modern, profesional, clean light background",
    token: {
      palette: {
        primary: "#4F46E5",
        accent: "#06B6D4",
        background: "#F8FAFC",
        surface: "#FFFFFF",
        text: "#0F172A",
      },
      typography: {
        heading_font: "Outfit",
        body_font: "Inter",
        heading_weight: "700",
        heading_size_hero: "3.75rem",
      },
      layout: {
        corner_radius: "soft",
        section_spacing: "normal",
      },
      theme_mode: "light",
    },
  },
  {
    id: "dark-futuristic",
    name: "Dark Futuristic (Neon Cyan)",
    description: "Tema gelap tech & web3 dengan glow kontras tinggi",
    token: {
      palette: {
        primary: "#06B6D4",
        accent: "#A855F7",
        background: "#090D16",
        surface: "#111827",
        text: "#F1F5F9",
      },
      dark_palette: {
        primary: "#06B6D4",
        accent: "#A855F7",
        background: "#090D16",
        surface: "#111827",
        text: "#F1F5F9",
      },
      typography: {
        heading_font: "Space Grotesk",
        body_font: "Inter",
        heading_weight: "700",
        heading_size_hero: "3.75rem",
      },
      layout: {
        corner_radius: "soft",
        section_spacing: "normal",
      },
      theme_mode: "dark",
    },
  },
  {
    id: "warm-culinary",
    name: "Warm Culinary (Amber & Terracotta)",
    description: "Hangat, menggugah selera untuk kafe, resto, & F&B",
    token: {
      palette: {
        primary: "#D97706",
        accent: "#DC2626",
        background: "#FFFBEB",
        surface: "#FFFFFF",
        text: "#451A03",
      },
      typography: {
        heading_font: "Playfair Display",
        body_font: "Plus Jakarta Sans",
        heading_weight: "700",
        heading_size_hero: "3.75rem",
      },
      layout: {
        corner_radius: "soft",
        section_spacing: "normal",
      },
      theme_mode: "light",
    },
  },
  {
    id: "natural-organic",
    name: "Natural Organic (Emerald & Forest)",
    description: "Nuansa alami, ramah lingkungan, wellness & artisan",
    token: {
      palette: {
        primary: "#059669",
        accent: "#10B981",
        background: "#F0FDF4",
        surface: "#FFFFFF",
        text: "#064E3B",
      },
      typography: {
        heading_font: "Fraunces",
        body_font: "Plus Jakarta Sans",
        heading_weight: "600",
        heading_size_hero: "3.75rem",
      },
      layout: {
        corner_radius: "rounded",
        section_spacing: "relaxed",
      },
      theme_mode: "light",
    },
  },
  {
    id: "luxury-gold",
    name: "Luxury Obsidian (Gold & Black)",
    description: "Eksklusif, elegan premium untuk portofolio & boutique",
    token: {
      palette: {
        primary: "#EAB308",
        accent: "#CA8A04",
        background: "#0A0A0A",
        surface: "#18181B",
        text: "#F4F4F5",
      },
      dark_palette: {
        primary: "#EAB308",
        accent: "#CA8A04",
        background: "#0A0A0A",
        surface: "#18181B",
        text: "#F4F4F5",
      },
      typography: {
        heading_font: "Cinzel",
        body_font: "Inter",
        heading_weight: "700",
        heading_size_hero: "3.75rem",
      },
      layout: {
        corner_radius: "sharp",
        section_spacing: "relaxed",
      },
      theme_mode: "dark",
    },
  },
  {
    id: "neo-brutalist",
    name: "Neo-Brutalist (Monochrome + Accent)",
    description: "Border tegas, kontras tinggi, ekspresif dan berani",
    token: {
      palette: {
        primary: "#F59E0B",
        accent: "#EC4899",
        background: "#FFFDF0",
        surface: "#FFFFFF",
        text: "#000000",
      },
      typography: {
        heading_font: "Bricolage Grotesque",
        body_font: "Plus Jakarta Sans",
        heading_weight: "800",
        heading_size_hero: "4rem",
      },
      layout: {
        corner_radius: "sharp",
        section_spacing: "normal",
      },
      theme_mode: "light",
    },
  },
];

export const MOCK_SHOWCASE_DATA = {
  header: {
    brand_name: "Webjoz Studio",
    tagline: "Karya Digital & Solusi Bisnis Kreatif",
    logo_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80",
    nav_links: [
      { label: "Tentang Kami", href: "#about" },
      { label: "Keunggulan", href: "#benefits" },
      { label: "Katalog", href: "#catalog" },
      { label: "Menu", href: "#menu" },
      { label: "Portofolio", href: "#works" },
      { label: "Harga", href: "#pricing" },
      { label: "Kontak", href: "#contact" },
    ],
    cta_text: "Konsultasi Gratis",
    cta_url: "#contact",
  },
  hero: {
    badge: "Solusi Terpercaya 2026",
    headline: "Bangun Kehadiran Digital Terbaik untuk Bisnis Anda",
    subheadline: "Platform pembuatan website cerdas, cepat, dan teroptimasi untuk konversi tinggi dengan desain estetis modern.",
    cta_text: "Mulai Sekarang",
    cta_url: "#pricing",
    secondary_cta_text: "Pelajari Lebih Lanjut",
    secondary_cta_url: "#about",
    image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80",
    portrait_image_url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=800&auto=format&fit=crop&q=80",
    stats: [
      { value: "500+", label: "Klien Puas" },
      { value: "99.9%", label: "Uptime Sistem" },
      { value: "10x", label: "Peningkatan Konversi" },
    ],
    badges: [
      { text: "Terverifikasi Resmi", icon: "shield-check" },
      { text: "Rating 4.9/5", icon: "star" },
      { text: "Dukungan 24/7", icon: "clock" },
    ],
    tags: ["Web Design", "SEO Ready", "E-Commerce", "High Speed"],
    accessories: [
      {
        type: "rating",
        label: "Kepuasan Klien",
        value: "4.9 / 5.0 (2,400+ ulasan)",
      },
      {
        type: "availability",
        label: "Ketersediaan Layanan",
        value: "Siap menerima proyek baru",
      },
    ],
    dashboard_widget: {
      tab_analytics_label: "Trafik & Penjualan",
      tab_deploy_label: "Deployment",
      tab_monitor_label: "Status Server",
      monitor_uptime_value: "99.98%",
      monitor_uptime_label: "Uptime Bulanan",
      monitor_latency_value: "28ms",
      monitor_latency_label: "Respons Global",
      monitor_errors_value: "0.01%",
      monitor_errors_label: "Error Rate",
      deploy_step_1: "Inisialisasi server & CDN edge",
      deploy_step_2: "Optimasi aset gambar & caching",
      deploy_step_3: "Situs siap melayani pengunjung",
    },
  },
  about: {
    eyebrow: "Tentang Kami",
    title: "Mendedikasikan Diri untuk Standar Visual Terbaik",
    body: "Kami adalah tim desainer, engineer, dan strategis digital yang berdedikasi menciptakan pengalaman web berkelas tinggi. Setiap detail dirancang untuk memberikan dampak nyata pada pertumbuhan bisnis Anda.",
    image_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1000&auto=format&fit=crop&q=80",
    highlights: [
      "Lebih dari 8 tahun pengalaman dalam rekayasa website",
      "Kombinasi estetika kontemporer dan performa ultra-cepat",
      "Fokus pada konversi penjualan dan kemudahan navigasi",
      "Dukungan purnajual dan pemeliharaan berkesinambungan",
    ],
    stats: [
      { value: "120+", label: "Proyek Terselesaikan" },
      { value: "98%", label: "Tingkat Kepuasan" },
      { value: "15+", label: "Penghargaan Desain" },
    ],
    milestones: [
      { year: "2020", title: "Awal Berdiri", description: "Memulai sebagai studio desain independen dengan fokus pada brand lokal." },
      { year: "2022", title: "Ekspansi Digital", description: "Meluncurkan platform otomasi web builder dan menjangkau ribuan pengguna." },
      { year: "2024", title: "Inovasi AI & Edge", description: "Mengintegrasikan generasi desain cerdas dengan arsitektur web modern." },
      { year: "2026", title: "Standar Baru Industri", description: "Menjadi pilihan utama UMKM dan profesional untuk website bereputasi tinggi." },
    ],
    team_members: [
      {
        name: "Adipati Arya",
        role: "Chief Creative Officer",
        bio: "Berpengalaman 10 tahun memimpin arahan artistik dan branding global.",
        avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80",
      },
      {
        name: "Clarissa Dewi",
        role: "Head of Engineering",
        bio: "Fokus pada kecepatan rendering, arsitektur micro-frontend, dan keamanan data.",
        avatar_url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80",
      },
      {
        name: "Rian Pratama",
        role: "Lead UI/UX Architect",
        bio: "Spesialis dalam sistem tipografi modular dan micro-animations interaktif.",
        avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80",
      },
    ],
  },
  benefits: {
    eyebrow: "Keunggulan Kami",
    title: "Mengapa Memilih Layanan Kami?",
    subtitle: "Fitur dan keunggulan dirancang untuk memberi Anda daya saing maksimal di pasar digital.",
    items: [
      {
        title: "Performa Kecepatan Tinggi",
        description: "Waktu muat di bawah 1 detik dengan optimasi CDN global dan caching cerdas.",
        icon: "zap",
        stat: "99/100",
        stat_label: "Google PageSpeed",
      },
      {
        title: "Desain Responsif Sempurna",
        description: "Tampilan mulus di ponsel, tablet, laptop, hingga layar monitor ultra-lebar.",
        icon: "smartphone",
        stat: "100%",
        stat_label: "Mobile Friendly",
      },
      {
        title: "Keamanan Tingkat Lanjut",
        description: "Perlindungan SSL otomatis, proteksi brute-force, dan isolasi data per akun.",
        icon: "shield",
        stat: "256-bit",
        stat_label: "Enkripsi Data",
      },
      {
        title: "Struktur SEO Terarah",
        description: "Markup schema, metadata otomatis, dan sitemap dinamis agar mudah ditemukan di Google.",
        icon: "search",
        stat: "3x",
        stat_label: "Trafik Organik",
      },
      {
        title: "Kemudahan Kustomisasi",
        description: "Editor intuitif tanpa perlu coding rumit, ubah teks dan gambar secara instan.",
        icon: "sliders",
        stat: "5 Menit",
        stat_label: "Waktu Setup",
      },
      {
        title: "Dukungan Prioritas 24/7",
        description: "Tim ahli kami selalu siap membantu via WhatsApp dan email kapan pun Anda butuh.",
        icon: "headphones",
        stat: "15 Menit",
        stat_label: "Rata-rata Respon",
      },
    ],
    comparison: {
      competitor_name: "Web Konvensional",
      rows: [
        { feature: "Waktu Pengerjaan", us: "1-2 Hari Kerja", them: "3-4 Minggu" },
        { feature: "Optimasi Mobile & SEO", us: "Bawaan Siap Pakai", them: "Biaya Tambahan" },
        { feature: "Biaya Pemeliharaan", us: "Sudah Termasuk", them: "Bulanan Mahal" },
        { feature: "Kemudahan Edit Konten", us: "Editor Mandiri", them: "Harus Hubungi Webmaster" },
      ],
    },
  },
  menu: {
    eyebrow: "Menu Kami",
    title: "Daftar Menu Pilihan",
    subtitle: "Diracik dari bahan berkualitas tinggi untuk sensasi rasa tak terlupakan.",
    categories: [
      {
        id: "cat-1",
        name: "Makanan Utama",
        items: [
          {
            id: "m-1",
            name: "Nasi Campur Bali Komplit",
            description: "Ayam suwir betutu, sate lilit ikan, lawar sayur segar, dan sambal matah harum.",
            price: "Rp 45.000",
            promo_price: "Rp 38.000",
            badge: "Chef's Signature",
            tags: ["Favorit", "Pedas"],
            image_url: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&auto=format&fit=crop&q=80",
          },
          {
            id: "m-2",
            name: "Bebek Goreng Renyah Kremes",
            description: "Bebek bumbu rempah kuning digoreng garing renyah disajikan dengan lalapan dan sambal korek.",
            price: "Rp 55.000",
            badge: "Best Seller",
            tags: ["Gurih", "Renyah"],
            image_url: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&auto=format&fit=crop&q=80",
          },
          {
            id: "m-3",
            name: "Sate Wagyu Maranggi",
            description: "Daging wagyu melt-in-mouth dipanggang arang dengan rendaman rempah khas Purwakarta.",
            price: "Rp 75.000",
            badge: "Premium",
            tags: ["Wagyu", "Empuk"],
            image_url: "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600&auto=format&fit=crop&q=80",
          },
        ],
      },
      {
        id: "cat-2",
        name: "Minuman & Kopi",
        items: [
          {
            id: "m-4",
            name: "Kopi Susu Gula Aren Spesial",
            description: "Espresso arabika Nusantara dengan susu oat gurih dan sirup gula aren murni.",
            price: "Rp 24.000",
            badge: "Populer",
            tags: ["Dingin", "Manis Pas"],
            image_url: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&auto=format&fit=crop&q=80",
          },
          {
            id: "m-5",
            name: "Artisan Matcha Latte",
            description: "Ceremonial grade matcha Jepang berpadu dengan susu steamed lembut.",
            price: "Rp 32.000",
            tags: ["Non-Coffee"],
            image_url: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&auto=format&fit=crop&q=80",
          },
        ],
      },
    ],
  },
  catalog: {
    eyebrow: "Pilihan Terbaik",
    title: "Koleksi Produk Unggulan",
    subtitle: "Eksplorasi ragam pilihan produk berkualitas yang siap memenuhi kebutuhan Anda.",
    categories: [
      {
        id: "cat-p1",
        name: "Produk Fisik",
        items: [
          {
            id: "c-1",
            name: "Kursi Ergonomis Pro",
            description: "Lumbar support adaptif dan breathable mesh fabric untuk kerja seharian.",
            price: "Rp 2.499.000",
            promo_price: "Rp 1.999.000",
            badge: "Paling Laris",
            features: ["Garansi 5 Tahun", "Adjustable Armrest", "Breathable Mesh"],
            image_url: "https://images.unsplash.com/photo-1580481077195-c328a37db71a?w=600&auto=format&fit=crop&q=80",
          },
          {
            id: "c-2",
            name: "Meja Kayu Ek Solid",
            description: "Meja kerja minimalis dengan manajemen kabel tersembunyi.",
            price: "Rp 3.850.000",
            features: ["Kayu Ek Solid", "Kabel Organizer", "Finishing Tahan Air"],
            image_url: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&auto=format&fit=crop&q=80",
          },
          {
            id: "c-3",
            name: "Monitor Stand Aluminium",
            description: "Dudukan monitor ganda dari paduan aluminium anodized matte.",
            price: "Rp 850.000",
            promo_price: "Rp 720.000",
            badge: "Diskon 15%",
            features: ["Aluminium Padat", "Muat 2 Monitor", "Slot Penyimpanan"],
            image_url: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=600&auto=format&fit=crop&q=80",
          },
        ],
      },
      {
        id: "cat-p2",
        name: "Aksesoris",
        items: [
          {
            id: "c-4",
            name: "Desk Mat Kulit Vegan",
            description: "Alas meja tahan tumpahan air dengan jahitan presisi.",
            price: "Rp 275.000",
            features: ["Waterproof", "Lembut untuk Mouse", "Mudah Dibersihkan"],
            image_url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&auto=format&fit=crop&q=80",
          },
        ],
      },
    ],
  },
  works: {
    eyebrow: "Portofolio",
    title: "Portofolio & Proyek Pilihan",
    subtitle: "Cuplikan karya terpilih yang telah membantu klien kami mencapai tujuan bisnisnya.",
    items: [
      {
        title: "Redesain Platform FinTech Nusantara",
        category: "Mobile & Web App",
        year: "2025",
        client: "PT Finansial Maju",
        description: "Meningkatkan engagement pengguna sebesar 42% melalui antarmuka bersih dan onboarding interaktif.",
        image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
        project_url: "#",
      },
      {
        title: "Identitas Visual & E-Commerce Kopi Gayo",
        category: "Branding & Store",
        year: "2025",
        client: "Gayo Roastery",
        description: "Pengembangan toko online direct-to-consumer dengan sistem checkout WhatsApp terotomasi.",
        image_url: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop&q=80",
        project_url: "#",
      },
      {
        title: "Situs Korporat Green Energy Indonesia",
        category: "Corporate Website",
        year: "2024",
        client: "Energi Bersih Nusantara",
        description: "Landing page interaktif dengan visual storytelling data emisi karbon real-time.",
        image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
        project_url: "#",
      },
      {
        title: "Aplikasi Reservasi Klinik Estetika",
        category: "Web Application",
        year: "2024",
        client: "Aura Glow Clinic",
        description: "Sistem jadwal dokter dan pembayaran instan dengan tingkat kehadiran janji temu 94%.",
        image_url: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&auto=format&fit=crop&q=80",
        project_url: "#",
      },
    ],
  },
  gallery: {
    eyebrow: "Galeri",
    title: "Galeri Visual & Suasana",
    items: [
      {
        image_url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80",
        caption: "Ruang Kolaborasi Kreatif",
      },
      {
        image_url: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=800&auto=format&fit=crop&q=80",
        caption: "Proses Wireframing & Prototyping",
      },
      {
        image_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&auto=format&fit=crop&q=80",
        caption: "Sesi Diskusi Strategi Produk",
      },
      {
        image_url: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800&auto=format&fit=crop&q=80",
        caption: "Workshop Desain Bersama Klien",
      },
      {
        image_url: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&auto=format&fit=crop&q=80",
        caption: "Suasana Kerja Dinamis",
      },
      {
        image_url: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?w=800&auto=format&fit=crop&q=80",
        caption: "Penyempurnaan Detail Visual",
      },
    ],
    before_after: {
      before_image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80",
      after_image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
      before_label: "Desain Lama",
      after_label: "Hasil Redesain Baru",
    },
  },
  stats: {
    eyebrow: "Angka Nyata",
    title: "Pencapaian dalam Angka",
    subtitle: "Metrik nyata yang mencerminkan dedikasi dan kepercayaan dari para pengguna kami.",
    items: [
      { value: "1,500+", label: "Website Aktif", description: "Melayani puluhan ribu pengunjung setiap hari" },
      { value: "99.98%", label: "Tingkat Uptime", description: "Infrastruktur cloud berstandar enterprise" },
      { value: "4.9/5", label: "Skor Kepuasan", description: "Berdasarkan lebih dari 800+ ulasan independen" },
      { value: "< 24 Jam", label: "Waktu Penerbitan", description: "Proses cepat dari konsep ke online" },
    ],
  },
  testimonials: {
    eyebrow: "Testimoni",
    title: "Apa Kata Mereka?",
    subtitle: "Cerita sukses dan pengalaman nyata dari mereka yang telah mempercayakan kehadiran webnya kepada kami.",
    items: [
      {
        quote: "Website baru kami meningkatkan lead pelanggan masuk hingga 3 kali lipat dalam bulan pertama peluncuran. Desainnya sangat profesional!",
        name: "Hendra Gunawan",
        role: "Founder & CEO",
        company: "PT Logistik Handal",
        avatar_initials: "HG",
        avatar_color: "#4F46E5",
        rating: 5,
        source: "google",
      },
      {
        quote: "Tampilan responsif dan cepat banget! Pelanggan kafe kami sering memuji kemudahan melihat menu dan pesan online lewat website.",
        name: "Siti Rahmawati",
        role: "Pemilik Bisnis",
        company: "Kopi Seduh Senja",
        avatar_initials: "SR",
        avatar_color: "#D97706",
        rating: 5,
        source: "google",
      },
      {
        quote: "Tim sangat komunikatif dan eksekusi desainnya melebihi ekspektasi kami. Layanan purnajualnya juga sangat responsif.",
        name: "Budi Santoso",
        role: "Marketing Director",
        company: "Nusantara Property",
        avatar_initials: "BS",
        avatar_color: "#059669",
        rating: 5,
        source: "google",
      },
    ],
  },
  partners: {
    eyebrow: "Mitra Kami",
    title: "Dipercaya oleh Brand Terkemuka",
    subtitle: "Berkolaborasi bersama berbagai perusahaan inovatif di seluruh nusantara.",
    items: [
      { name: "Bank Mandiri", category: "Finansial" },
      { name: "Telkomsel", category: "Telekomunikasi" },
      { name: "Gojek", category: "Teknologi" },
      { name: "Tokopedia", category: "E-Commerce" },
      { name: "Astra International", category: "Otomotif" },
      { name: "Indofood", category: "F&B" },
    ],
  },
  pricing: {
    eyebrow: "Harga",
    title: "Pilihan Paket Investasi",
    subtitle: "Harga transparan tanpa biaya tersembunyi. Pilih paket yang paling pas untuk skala usaha Anda.",
    plans: [
      {
        name: "Starter",
        price: "Rp 299.000",
        period: "/ tahun",
        description: "Ideal untuk portofolio pribadi, UMKM pemula, atau kartu nama digital.",
        features: [
          "1 Domain Website Kustom",
          "Hingga 5 Halaman Konten",
          "Sertifikat SSL Gratis",
          "Integrasi Tombol WhatsApp",
          "Hosting Cloud Standar",
        ],
        cta_text: "Pilih Paket Starter",
        cta_url: "#contact",
      },
      {
        name: "Professional",
        price: "Rp 599.000",
        period: "/ tahun",
        description: "Solusi lengkap untuk bisnis berkembang yang butuh katalog dan konversi maksimal.",
        is_featured: true,
        badge: "Paling Populer",
        features: [
          "Semua Fitur Starter",
          "Halaman Tak Terbatas",
          "Katalog Produk & Menu Interaktif",
          "Integrasi Google Analytics & SEO",
          "Prioritas Support WhatsApp 24/7",
          "Performa Kecepatan Ultra-Fast CDN",
        ],
        cta_text: "Mulai Paket Pro",
        cta_url: "#contact",
      },
      {
        name: "Enterprise",
        price: "Rp 1.499.000",
        period: "/ tahun",
        description: "Untuk korporasi dan brand dengan kebutuhan fitur kustom dan integrasi mendalam.",
        features: [
          "Semua Fitur Professional",
          "Custom API Integration",
          "Dedicated Server Instance",
          "Audit Desain & UX Berkala",
          "SLA Uptime 99.99%",
          "Dedicated Account Manager",
        ],
        cta_text: "Hubungi Sales",
        cta_url: "#contact",
      },
    ],
  },
  faq: {
    title: "Pertanyaan yang Sering Diajukan",
    items: [
      {
        question: "Berapa lama waktu yang dibutuhkan hingga website siap tayang?",
        answer: "Dengan teknologi builder kami, website Anda dapat langsung aktif dalam hitungan jam setelah konten dasar selesai diatur. Pengerjaan kustom umumnya membutuhkan 1-3 hari kerja.",
        category: "Umum",
      },
      {
        question: "Apakah saya bisa mengubah konten website sendiri di kemudian hari?",
        answer: "Tentu saja! Anda diberikan akses dashboard visual yang sangat mudah digunakan untuk mengganti foto, memperbarui harga menu/katalog, dan mengedit teks tanpa perlu kemampuan coding.",
        category: "Pengelolaan",
      },
      {
        question: "Bagaimana dengan domain (.com / .id) dan hosting?",
        answer: "Paket kami sudah mencakup hosting awan berkecepatan tinggi dengan sertifikat keamanan SSL gratis. Anda juga dapat menghubungkan domain pribadi Anda dengan mudah.",
        category: "Teknis",
      },
      {
        question: "Apakah website ini sudah ramah pengguna mobile dan SEO?",
        answer: "Ya, 100% responsif di semua perangkat dan otomatis terpasang struktur metadata SEO agar mudah diindeks oleh mesin pencari Google.",
        category: "Teknis",
      },
    ],
  },
  cta: {
    headline: "Siap Membawa Bisnis Anda ke Level Berikutnya?",
    subheadline: "Konsultasikan kebutuhan kehadiran digital Anda bersama tim ahli kami hari ini tanpa komitmen.",
    cta_text: "Mulai Konsultasi Gratis",
    cta_url: "#contact",
    secondary_cta_text: "Lihat Contoh Website",
    secondary_cta_url: "#works",
    image_url: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=1000&auto=format&fit=crop&q=80",
  },
  contact: {
    eyebrow: "Kontak",
    title: "Hubungi Kami",
    subtitle: "Kami siap mendengar ide dan kebutuhan Anda. Kunjungi kantor kami atau kirim pesan cepat melalui WhatsApp.",
    phone: "+62 812-3456-7890",
    email: "halo@webjoz.id",
    address: "Jl. Giwangan No. 45, Umbulharjo, D.I. Yogyakarta 55163",
    hours: "Senin - Sabtu: 08:30 - 17:00 WIB",
    whatsapp: "6281234567890",
    map_embed_url: "https://maps.google.com/maps?q=-7.8288,110.3922&hl=id&z=14&output=embed",
  },
  footer: {
    brand_name: "Webjoz Studio",
    description: "Platform pembuatan website modern bertenaga generasi cerdas, didesain untuk UMKM dan kreator digital Indonesia.",
    copyright: "© 2026 Webjoz Studio. Hak Cipta Dilindungi.",
    address: "Yogyakarta, Indonesia",
    hours: "08:30 - 17:00 WIB",
    social_links: [
      { platform: "instagram", url: "https://instagram.com" },
      { platform: "whatsapp", url: "https://wa.me/6281234567890" },
      { platform: "linkedin", url: "https://linkedin.com" },
      { platform: "youtube", url: "https://youtube.com" },
    ],
  },
  blog: {
    posts: [
      {
        id: 1,
        title: "5 Tren Desain Web 2026 yang Terbukti Meningkatkan Konversi Bisnis",
        slug: "tren-desain-web-2026",
        excerpt: "Pelajari bagaimana tata letak bento grid, tipografi ekspresif, dan micro-interaction memengaruhi psikologi belanja pengunjung web.",
        content_html: "<p>Artikel lengkap seputar tren desain...</p>",
        cover_image_url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
        published_at: "2026-03-15",
        created_at: "2026-03-15",
      },
      {
        id: 2,
        title: "Panduan Optimasi Google PageSpeed untuk Pemilik Toko Online",
        slug: "panduan-optimasi-pagespeed",
        excerpt: "Langkah demi langkah kompresi gambar generasi berikutnya dan pemanfaatan edge cache untuk skor 95+ di Core Web Vitals.",
        content_html: "<p>Tips teknis optimasi kecepatan web...</p>",
        cover_image_url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80",
        published_at: "2026-03-10",
        created_at: "2026-03-10",
      },
      {
        id: 3,
        title: "Strategi Copywriting Landing Page yang Menghipnotis Pelanggan",
        slug: "strategi-copywriting-landing-page",
        excerpt: "Formula headline kuat, penempatan social proof yang tepat, dan panggilan aksi (CTA) yang tidak bisa ditolak.",
        content_html: "<p>Struktur copywriting yang terbukti berhasil...</p>",
        cover_image_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&auto=format&fit=crop&q=80",
        published_at: "2026-03-01",
        created_at: "2026-03-01",
      },
    ],
  },
};
