/**
 * Lightweight, zero-dependency Indonesian postal code (kodepos) mapper.
 * Instantly resolves Indonesian 5-digit postal codes to City/Regency and Province.
 */

interface PostalMatch {
  city: string;
  state: string;
}

// 3-digit prefix high-accuracy table
const PREFIX_3_MAP: Record<string, PostalMatch> = {
  // DKI Jakarta
  "101": { city: "Jakarta Pusat", state: "DKI Jakarta" },
  "102": { city: "Jakarta Pusat", state: "DKI Jakarta" },
  "103": { city: "Jakarta Pusat", state: "DKI Jakarta" },
  "104": { city: "Jakarta Pusat", state: "DKI Jakarta" },
  "105": { city: "Jakarta Pusat", state: "DKI Jakarta" },
  "106": { city: "Jakarta Pusat", state: "DKI Jakarta" },
  "107": { city: "Jakarta Pusat", state: "DKI Jakarta" },
  "111": { city: "Jakarta Barat", state: "DKI Jakarta" },
  "112": { city: "Jakarta Barat", state: "DKI Jakarta" },
  "113": { city: "Jakarta Barat", state: "DKI Jakarta" },
  "114": { city: "Jakarta Barat", state: "DKI Jakarta" },
  "115": { city: "Jakarta Barat", state: "DKI Jakarta" },
  "116": { city: "Jakarta Barat", state: "DKI Jakarta" },
  "117": { city: "Jakarta Barat", state: "DKI Jakarta" },
  "118": { city: "Jakarta Barat", state: "DKI Jakarta" },
  "121": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "122": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "123": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "124": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "125": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "126": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "127": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "128": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "129": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "131": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "132": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "133": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "134": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "135": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "136": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "137": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "138": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "139": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "141": { city: "Jakarta Utara", state: "DKI Jakarta" },
  "142": { city: "Jakarta Utara", state: "DKI Jakarta" },
  "143": { city: "Jakarta Utara", state: "DKI Jakarta" },
  "144": { city: "Jakarta Utara", state: "DKI Jakarta" },
  "145": { city: "Kepulauan Seribu", state: "DKI Jakarta" },

  // Banten
  "151": { city: "Kota Tangerang", state: "Banten" },
  "152": { city: "Kota Tangerang Selatan", state: "Banten" },
  "153": { city: "Kota Tangerang Selatan", state: "Banten" },
  "154": { city: "Kota Tangerang Selatan", state: "Banten" },
  "155": { city: "Kabupaten Tangerang", state: "Banten" },
  "156": { city: "Kabupaten Tangerang", state: "Banten" },
  "157": { city: "Kabupaten Tangerang", state: "Banten" },
  "158": { city: "Kabupaten Tangerang", state: "Banten" },
  "421": { city: "Kota Serang", state: "Banten" },
  "422": { city: "Kabupaten Pandeglang", state: "Banten" },
  "423": { city: "Kabupaten Lebak", state: "Banten" },
  "424": { city: "Kota Cilegon", state: "Banten" },

  // Jawa Barat
  "161": { city: "Kota Bogor", state: "Jawa Barat" },
  "162": { city: "Kabupaten Bogor", state: "Jawa Barat" },
  "163": { city: "Kabupaten Bogor", state: "Jawa Barat" },
  "164": { city: "Kota Depok", state: "Jawa Barat" },
  "165": { city: "Kota Depok", state: "Jawa Barat" },
  "166": { city: "Kabupaten Bogor", state: "Jawa Barat" },
  "167": { city: "Kabupaten Bogor", state: "Jawa Barat" },
  "168": { city: "Kabupaten Bogor", state: "Jawa Barat" },
  "169": { city: "Kabupaten Bogor", state: "Jawa Barat" },
  "171": { city: "Kota Bekasi", state: "Jawa Barat" },
  "172": { city: "Kota Bekasi", state: "Jawa Barat" },
  "173": { city: "Kota Bekasi", state: "Jawa Barat" },
  "174": { city: "Kota Bekasi", state: "Jawa Barat" },
  "175": { city: "Kabupaten Bekasi", state: "Jawa Barat" },
  "176": { city: "Kabupaten Bekasi", state: "Jawa Barat" },
  "177": { city: "Kabupaten Bekasi", state: "Jawa Barat" },
  "401": { city: "Kota Bandung", state: "Jawa Barat" },
  "402": { city: "Kota Bandung", state: "Jawa Barat" },
  "403": { city: "Kabupaten Bandung", state: "Jawa Barat" },
  "405": { city: "Kota Cimahi", state: "Jawa Barat" },
  "409": { city: "Kabupaten Bandung Barat", state: "Jawa Barat" },
  "411": { city: "Kabupaten Purwakarta", state: "Jawa Barat" },
  "412": { city: "Kabupaten Subang", state: "Jawa Barat" },
  "413": { city: "Kabupaten Karawang", state: "Jawa Barat" },
  "431": { city: "Kota Sukabumi", state: "Jawa Barat" },
  "432": { city: "Kabupaten Cianjur", state: "Jawa Barat" },
  "433": { city: "Kabupaten Sukabumi", state: "Jawa Barat" },
  "441": { city: "Kabupaten Garut", state: "Jawa Barat" },
  "451": { city: "Kota Cirebon", state: "Jawa Barat" },
  "452": { city: "Kabupaten Indramayu", state: "Jawa Barat" },
  "453": { city: "Kabupaten Sumedang", state: "Jawa Barat" },
  "454": { city: "Kabupaten Majalengka", state: "Jawa Barat" },
  "455": { city: "Kabupaten Kuningan", state: "Jawa Barat" },
  "461": { city: "Kota Tasikmalaya", state: "Jawa Barat" },
  "462": { city: "Kabupaten Ciamis", state: "Jawa Barat" },
  "463": { city: "Kota Banjar", state: "Jawa Barat" },
  "464": { city: "Kabupaten Tasikmalaya", state: "Jawa Barat" },
  "465": { city: "Kabupaten Pangandaran", state: "Jawa Barat" },

  // DI Yogyakarta
  "551": { city: "Kota Yogyakarta", state: "DI Yogyakarta" },
  "552": { city: "Kota Yogyakarta", state: "DI Yogyakarta" },
  "555": { city: "Kabupaten Sleman", state: "DI Yogyakarta" },
  "556": { city: "Kabupaten Kulon Progo", state: "DI Yogyakarta" },
  "557": { city: "Kabupaten Bantul", state: "DI Yogyakarta" },
  "558": { city: "Kabupaten Gunungkidul", state: "DI Yogyakarta" },

  // Jawa Tengah
  "501": { city: "Kota Semarang", state: "Jawa Tengah" },
  "502": { city: "Kota Semarang", state: "Jawa Tengah" },
  "505": { city: "Kabupaten Semarang", state: "Jawa Tengah" },
  "506": { city: "Kabupaten Grobogan", state: "Jawa Tengah" },
  "507": { city: "Kota Salatiga", state: "Jawa Tengah" },
  "511": { city: "Kota Pekalongan", state: "Jawa Tengah" },
  "512": { city: "Kabupaten Batang", state: "Jawa Tengah" },
  "513": { city: "Kabupaten Kendal", state: "Jawa Tengah" },
  "521": { city: "Kota Tegal", state: "Jawa Tengah" },
  "522": { city: "Kabupaten Brebes", state: "Jawa Tengah" },
  "523": { city: "Kabupaten Pemalang", state: "Jawa Tengah" },
  "524": { city: "Kabupaten Tegal", state: "Jawa Tengah" },
  "531": { city: "Kabupaten Banyumas", state: "Jawa Tengah" },
  "532": { city: "Kabupaten Cilacap", state: "Jawa Tengah" },
  "533": { city: "Kabupaten Purbalingga", state: "Jawa Tengah" },
  "534": { city: "Kabupaten Banjarnegara", state: "Jawa Tengah" },
  "541": { city: "Kabupaten Purworejo", state: "Jawa Tengah" },
  "543": { city: "Kabupaten Kebumen", state: "Jawa Tengah" },
  "544": { city: "Kabupaten Kebumen", state: "Jawa Tengah" },
  "561": { city: "Kota Magelang", state: "Jawa Tengah" },
  "562": { city: "Kabupaten Temanggung", state: "Jawa Tengah" },
  "563": { city: "Kabupaten Wonosobo", state: "Jawa Tengah" },
  "565": { city: "Kabupaten Magelang", state: "Jawa Tengah" },
  "571": { city: "Kota Surakarta", state: "Jawa Tengah" },
  "572": { city: "Kabupaten Sragen", state: "Jawa Tengah" },
  "573": { city: "Kabupaten Boyolali", state: "Jawa Tengah" },
  "574": { city: "Kabupaten Klaten", state: "Jawa Tengah" },
  "575": { city: "Kabupaten Sukoharjo", state: "Jawa Tengah" },
  "576": { city: "Kabupaten Wonogiri", state: "Jawa Tengah" },
  "577": { city: "Kabupaten Karanganyar", state: "Jawa Tengah" },
  "581": { city: "Kabupaten Grobogan", state: "Jawa Tengah" },
  "582": { city: "Kabupaten Blora", state: "Jawa Tengah" },
  "591": { city: "Kabupaten Pati", state: "Jawa Tengah" },
  "592": { city: "Kabupaten Rembang", state: "Jawa Tengah" },
  "593": { city: "Kabupaten Kudus", state: "Jawa Tengah" },
  "594": { city: "Kabupaten Jepara", state: "Jawa Tengah" },
  "595": { city: "Kabupaten Demak", state: "Jawa Tengah" },

  // Jawa Timur
  "601": { city: "Kota Surabaya", state: "Jawa Timur" },
  "602": { city: "Kota Surabaya", state: "Jawa Timur" },
  "611": { city: "Kabupaten Gresik", state: "Jawa Timur" },
  "612": { city: "Kabupaten Sidoarjo", state: "Jawa Timur" },
  "613": { city: "Kota Mojokerto", state: "Jawa Timur" },
  "614": { city: "Kabupaten Jombang", state: "Jawa Timur" },
  "621": { city: "Kabupaten Bojonegoro", state: "Jawa Timur" },
  "622": { city: "Kabupaten Lamongan", state: "Jawa Timur" },
  "623": { city: "Kabupaten Tuban", state: "Jawa Timur" },
  "631": { city: "Kota Madiun", state: "Jawa Timur" },
  "632": { city: "Kabupaten Ngawi", state: "Jawa Timur" },
  "633": { city: "Kabupaten Magetan", state: "Jawa Timur" },
  "634": { city: "Kabupaten Ponorogo", state: "Jawa Timur" },
  "635": { city: "Kabupaten Pacitan", state: "Jawa Timur" },
  "641": { city: "Kota Kediri", state: "Jawa Timur" },
  "642": { city: "Kabupaten Nganjuk", state: "Jawa Timur" },
  "643": { city: "Kabupaten Trenggalek", state: "Jawa Timur" },
  "644": { city: "Kabupaten Tulungagung", state: "Jawa Timur" },
  "651": { city: "Kota Malang", state: "Jawa Timur" },
  "652": { city: "Kabupaten Malang", state: "Jawa Timur" },
  "653": { city: "Kota Batu", state: "Jawa Timur" },
  "661": { city: "Kota Blitar", state: "Jawa Timur" },
  "671": { city: "Kota Pasuruan", state: "Jawa Timur" },
  "672": { city: "Kota Probolinggo", state: "Jawa Timur" },
  "673": { city: "Kabupaten Lumajang", state: "Jawa Timur" },
  "681": { city: "Kabupaten Jember", state: "Jawa Timur" },
  "682": { city: "Kabupaten Bondowoso", state: "Jawa Timur" },
  "683": { city: "Kabupaten Situbondo", state: "Jawa Timur" },
  "684": { city: "Kabupaten Banyuwangi", state: "Jawa Timur" },
  "691": { city: "Kabupaten Bangkalan", state: "Jawa Timur" },
  "692": { city: "Kabupaten Sampang", state: "Jawa Timur" },
  "693": { city: "Kabupaten Pamekasan", state: "Jawa Timur" },
  "694": { city: "Kabupaten Sumenep", state: "Jawa Timur" },

  // Bali
  "801": { city: "Kota Denpasar", state: "Bali" },
  "802": { city: "Kota Denpasar", state: "Bali" },
  "803": { city: "Kabupaten Badung", state: "Bali" },
  "805": { city: "Kabupaten Gianyar", state: "Bali" },
  "821": { city: "Kabupaten Tabanan", state: "Bali" },
  "822": { city: "Kabupaten Jembrana", state: "Bali" },
  "828": { city: "Kabupaten Buleleng", state: "Bali" },

  // Sumatera
  "201": { city: "Kota Medan", state: "Sumatera Utara" },
  "202": { city: "Kota Medan", state: "Sumatera Utara" },
  "207": { city: "Kota Binjai", state: "Sumatera Utara" },
  "211": { city: "Kota Pematangsiantar", state: "Sumatera Utara" },
  "231": { city: "Kota Banda Aceh", state: "Aceh" },
  "243": { city: "Kota Lhokseumawe", state: "Aceh" },
  "251": { city: "Kota Padang", state: "Sumatera Barat" },
  "261": { city: "Kota Bukittinggi", state: "Sumatera Barat" },
  "281": { city: "Kota Pekanbaru", state: "Riau" },
  "288": { city: "Kota Dumai", state: "Riau" },
  "291": { city: "Kota Tanjung Pinang", state: "Kepulauan Riau" },
  "294": { city: "Kota Batam", state: "Kepulauan Riau" },
  "301": { city: "Kota Palembang", state: "Sumatera Selatan" },
  "302": { city: "Kota Palembang", state: "Sumatera Selatan" },
  "331": { city: "Kota Pangkal Pinang", state: "Kepulauan Bangka Belitung" },
  "341": { city: "Kota Bandar Lampung", state: "Lampung" },
  "361": { city: "Kota Jambi", state: "Jambi" },
  "381": { city: "Kota Bengkulu", state: "Bengkulu" },

  // Kalimantan
  "701": { city: "Kota Banjarmasin", state: "Kalimantan Selatan" },
  "707": { city: "Kota Banjarbaru", state: "Kalimantan Selatan" },
  "731": { city: "Kota Palangkaraya", state: "Kalimantan Tengah" },
  "751": { city: "Kota Samarinda", state: "Kalimantan Timur" },
  "761": { city: "Kota Balikpapan", state: "Kalimantan Timur" },
  "771": { city: "Kota Tarakan", state: "Kalimantan Utara" },
  "781": { city: "Kota Pontianak", state: "Kalimantan Barat" },
  "791": { city: "Kota Singkawang", state: "Kalimantan Barat" },

  // Sulawesi
  "901": { city: "Kota Makassar", state: "Sulawesi Selatan" },
  "902": { city: "Kota Makassar", state: "Sulawesi Selatan" },
  "911": { city: "Kota Parepare", state: "Sulawesi Selatan" },
  "919": { city: "Kota Palopo", state: "Sulawesi Selatan" },
  "913": { city: "Kabupaten Mamuju", state: "Sulawesi Barat" },
  "931": { city: "Kota Kendari", state: "Sulawesi Tenggara" },
  "937": { city: "Kota Baubau", state: "Sulawesi Tenggara" },
  "941": { city: "Kota Palu", state: "Sulawesi Tengah" },
  "951": { city: "Kota Manado", state: "Sulawesi Utara" },
  "955": { city: "Kota Bitung", state: "Sulawesi Utara" },
  "961": { city: "Kota Gorontalo", state: "Gorontalo" },

  // Maluku & Papua
  "971": { city: "Kota Ambon", state: "Maluku" },
  "977": { city: "Kota Ternate", state: "Maluku Utara" },
  "981": { city: "Kota Jayapura", state: "Papua" },
  "984": { city: "Kota Sorong", state: "Papua Barat Daya" },
  "996": { city: "Kabupaten Merauke", state: "Papua Selatan" },
};

// 2-digit fallback map for any other area
const PREFIX_2_MAP: Record<string, PostalMatch> = {
  "10": { city: "Jakarta Pusat", state: "DKI Jakarta" },
  "11": { city: "Jakarta Barat", state: "DKI Jakarta" },
  "12": { city: "Jakarta Selatan", state: "DKI Jakarta" },
  "13": { city: "Jakarta Timur", state: "DKI Jakarta" },
  "14": { city: "Jakarta Utara", state: "DKI Jakarta" },
  "15": { city: "Tangerang", state: "Banten" },
  "16": { city: "Bogor / Depok", state: "Jawa Barat" },
  "17": { city: "Bekasi", state: "Jawa Barat" },
  "20": { city: "Medan", state: "Sumatera Utara" },
  "21": { city: "Asahan / Batubara", state: "Sumatera Utara" },
  "22": { city: "Tapanuli", state: "Sumatera Utara" },
  "23": { city: "Banda Aceh", state: "Aceh" },
  "24": { city: "Aceh Timur / Utara", state: "Aceh" },
  "25": { city: "Padang", state: "Sumatera Barat" },
  "26": { city: "Bukittinggi", state: "Sumatera Barat" },
  "27": { city: "Solok", state: "Sumatera Barat" },
  "28": { city: "Pekanbaru", state: "Riau" },
  "29": { city: "Batam / Tanjungpinang", state: "Kepulauan Riau" },
  "30": { city: "Palembang", state: "Sumatera Selatan" },
  "31": { city: "Muara Enim / Lahat", state: "Sumatera Selatan" },
  "32": { city: "OKU", state: "Sumatera Selatan" },
  "33": { city: "Pangkal Pinang", state: "Kepulauan Bangka Belitung" },
  "34": { city: "Bandar Lampung", state: "Lampung" },
  "35": { city: "Lampung Selatan", state: "Lampung" },
  "36": { city: "Kota Jambi", state: "Jambi" },
  "37": { city: "Muaro Jambi / Bungo", state: "Jambi" },
  "38": { city: "Bengkulu", state: "Bengkulu" },
  "39": { city: "Rejang Lebong", state: "Bengkulu" },
  "40": { city: "Bandung", state: "Jawa Barat" },
  "41": { city: "Purwakarta / Karawang", state: "Jawa Barat" },
  "42": { city: "Serang", state: "Banten" },
  "43": { city: "Sukabumi / Cianjur", state: "Jawa Barat" },
  "44": { city: "Garut", state: "Jawa Barat" },
  "45": { city: "Cirebon / Kuningan", state: "Jawa Barat" },
  "46": { city: "Tasikmalaya / Ciamis", state: "Jawa Barat" },
  "50": { city: "Semarang", state: "Jawa Tengah" },
  "51": { city: "Pekalongan / Batang", state: "Jawa Tengah" },
  "52": { city: "Tegal / Brebes", state: "Jawa Tengah" },
  "53": { city: "Purwokerto / Banyumas", state: "Jawa Tengah" },
  "54": { city: "Purworejo / Kebumen", state: "Jawa Tengah" },
  "55": { city: "Kota Yogyakarta", state: "DI Yogyakarta" },
  "56": { city: "Magelang / Wonosobo", state: "Jawa Tengah" },
  "57": { city: "Surakarta (Solo)", state: "Jawa Tengah" },
  "58": { city: "Grobogan / Blora", state: "Jawa Tengah" },
  "59": { city: "Kudus / Jepara / Pati", state: "Jawa Tengah" },
  "60": { city: "Surabaya", state: "Jawa Timur" },
  "61": { city: "Sidoarjo / Gresik", state: "Jawa Timur" },
  "62": { city: "Bojonegoro / Tuban", state: "Jawa Timur" },
  "63": { city: "Madiun / Ponorogo", state: "Jawa Timur" },
  "64": { city: "Kediri / Tulungagung", state: "Jawa Timur" },
  "65": { city: "Malang", state: "Jawa Timur" },
  "66": { city: "Blitar", state: "Jawa Timur" },
  "67": { city: "Pasuruan / Probolinggo", state: "Jawa Timur" },
  "68": { city: "Jember / Banyuwangi", state: "Jawa Timur" },
  "69": { city: "Madura", state: "Jawa Timur" },
  "70": { city: "Banjarmasin", state: "Kalimantan Selatan" },
  "71": { city: "Hulu Sungai", state: "Kalimantan Selatan" },
  "72": { city: "Kotabaru", state: "Kalimantan Selatan" },
  "73": { city: "Palangkaraya", state: "Kalimantan Tengah" },
  "74": { city: "Kotawaringin", state: "Kalimantan Tengah" },
  "75": { city: "Samarinda", state: "Kalimantan Timur" },
  "76": { city: "Balikpapan", state: "Kalimantan Timur" },
  "77": { city: "Tarakan", state: "Kalimantan Utara" },
  "78": { city: "Pontianak", state: "Kalimantan Barat" },
  "79": { city: "Singkawang / Sambas", state: "Kalimantan Barat" },
  "80": { city: "Denpasar / Badung", state: "Bali" },
  "81": { city: "Buleleng", state: "Bali" },
  "82": { city: "Tabanan / Jembrana", state: "Bali" },
  "83": { city: "Mataram / Lombok", state: "Nusa Tenggara Barat" },
  "84": { city: "Sumbawa / Bima", state: "Nusa Tenggara Barat" },
  "85": { city: "Kupang", state: "Nusa Tenggara Timur" },
  "86": { city: "Flores", state: "Nusa Tenggara Timur" },
  "87": { city: "Sumba", state: "Nusa Tenggara Timur" },
  "90": { city: "Makassar", state: "Sulawesi Selatan" },
  "91": { city: "Parepare / Mamuju", state: "Sulawesi Selatan" },
  "92": { city: "Gowa / Bone", state: "Sulawesi Selatan" },
  "93": { city: "Kendari / Baubau", state: "Sulawesi Tenggara" },
  "94": { city: "Palu", state: "Sulawesi Tengah" },
  "95": { city: "Manado / Bitung", state: "Sulawesi Utara" },
  "96": { city: "Gorontalo", state: "Gorontalo" },
  "97": { city: "Ambon / Ternate", state: "Maluku" },
  "98": { city: "Jayapura / Sorong", state: "Papua" },
  "99": { city: "Merauke / Mimika", state: "Papua" },
};

/**
 * Resolves an Indonesian postal code to city and state.
 */
export function lookupIndonesianPostalCode(zip: string): PostalMatch | null {
  const clean = zip.trim().replace(/[^0-9]/g, "");
  if (clean.length < 3) return null;

  const p3 = clean.slice(0, 3);
  if (PREFIX_3_MAP[p3]) {
    return PREFIX_3_MAP[p3];
  }

  const p2 = clean.slice(0, 2);
  if (PREFIX_2_MAP[p2]) {
    return PREFIX_2_MAP[p2];
  }

  return null;
}
