import type { BusinessTypeItem, SubTypeItem, MoodItem } from "./types";

export const PENDING_KEY = "webjoz_pending_wizard_data";

export const MOOD_OPTIONS: MoodItem[] = [
  {
    value: "clean-modern",
    emoji: "🖥️",
    label: "Modern & Bersih",
    desc: "Bersih, rapi, dan profesional",
    palette: ["#FFFFFF", "#2563EB", "#0F172A"],
    font: "Space Grotesk",
    suitableFor: "Jasa, Korporat, Agency, Toko",
    dark: false,
  },
  {
    value: "warm-earthy",
    emoji: "🌿",
    label: "Hangat & Alami",
    desc: "Hangat, alami, dan bersahaja",
    palette: ["#F5F0E8", "#4D7C0F", "#92400E"],
    font: "Playfair Display",
    suitableFor: "Kafe, Kuliner, Organik, Handmade",
    dark: false,
  },
  {
    value: "bold-vibrant",
    emoji: "🎨",
    label: "Ceria & Berwarna",
    desc: "Ceria, ramah, dan penuh warna",
    palette: ["#FFF7ED", "#F97316", "#8B5CF6"],
    font: "Outfit",
    suitableFor: "Kuliner Kekinian, Fashion, Kreatif",
    dark: false,
  },
  {
    value: "dark-premium",
    emoji: "👑",
    label: "Elegan & Mewah",
    desc: "Gelap, mewah, dan eksklusif",
    palette: ["#0D0D0B", "#D4AF37", "#F5F0E8"],
    font: "Cormorant Garamond",
    suitableFor: "Hotel, Beauty Clinic, Perhiasan",
    dark: true,
  },
  {
    value: "bold-dark",
    emoji: "⚡",
    label: "Tegas & Berenergi",
    desc: "Kontras tinggi, tegas, dan bersemangat",
    palette: ["#0A0A0A", "#E63946", "#F4A261"],
    font: "Oswald",
    suitableFor: "Gym, Bengkel, Barbershop, Sport",
    dark: true,
  },
  {
    value: "retro",
    emoji: "⏰",
    label: "Klasik & Retro",
    desc: "Klasik, nostalgia, dan berkarakter",
    palette: ["#EFE6D5", "#8B4513", "#D97706"],
    font: "Merriweather",
    suitableFor: "Kopi Tradisional, Batik, Antik",
    dark: false,
  },
  {
    value: "futuristic",
    emoji: "🤖",
    label: "Futuristik",
    desc: "Modern, teknologi, dan futuristik",
    palette: ["#0B0F19", "#06B6D4", "#A855F7"],
    font: "Plus Jakarta Sans",
    suitableFor: "Tech Startup, SaaS, Digital",
    dark: true,
  },
];

export const INITIAL_MESSAGE = "Halo! Saya Jozz-ai dari Webjoz. Mau buat website bisnis, jasa, atau portofolio karya? Kita buat dalam 1 menit! Apa nama bisnis, brand, atau nama profesional Anda?";

export const AI_LOADING_STEPS = [
  "Menganalisis profil bisnis Anda...",
  "Merumuskan headline copywriting yang memikat...",
  "Menyusun cerita brand yang berkesan...",
  "Menyusun deskripsi layanan secara terstruktur...",
  "Merumuskan Pertanyaan Umum (FAQ) pelanggan...",
  "Mengatur optimasi tag metadata SEO...",
  "Merakit layout visual yang menawan...",
];

export const BUSINESS_TYPES: BusinessTypeItem[] = [
  { value: "Kuliner", emoji: "🍽️", label: "Kuliner", desc: "Restoran, Warung, Cafe & Catering" },
  { value: "Toko", emoji: "🛒", label: "Toko", desc: "Retail & Produk Fisik" },
  // "Portofolio" untuk kreator & profesional individual yang menampilkan karya
  { value: "Portofolio", emoji: "🎨", label: "Portofolio", desc: "Fotografer, Desainer, Developer, Kreator & Personal Brand" },
  // "Kreatif & Profesional" untuk agensi, tim, dan jasa profesional
  { value: "Kreatif & Profesional", emoji: "💼", label: "Kreatif & Profesional", desc: "Agency, Konsultan, Notaris & Jasa Profesional" },
  { value: "Company Profile", emoji: "🏢", label: "Company Profile", desc: "Properti, Konstruksi, Manufaktur, Yayasan, & Institusi" },
];

// Sub-tipe untuk "Portofolio" — kreator & profesional individual yang menampilkan karya
const PORTOFOLIO_PERSONAL_SUB_TYPES: SubTypeItem[] = [
  { value: "Fotografer", emoji: "📷", label: "Fotografer" },
  { value: "Videografer", emoji: "🎥", label: "Videografer" },
  { value: "Desainer", emoji: "🎨", label: "Desainer" },
  { value: "Ilustrator & Seniman", emoji: "🎭", label: "Ilustrator & Seniman" },
  { value: "Konten Kreator", emoji: "🎬", label: "Konten Kreator" },
  { value: "Developer & IT", emoji: "💻", label: "Developer & IT" },
  { value: "Penulis & Copywriter", emoji: "✍️", label: "Penulis & Copywriter" },
  { value: "Arsitek & Desainer Interior", emoji: "🏛️", label: "Arsitek & Interior" },
  { value: "Musisi & Entertainer", emoji: "🎵", label: "Musisi & Hiburan" },
];

// Sub-tipe untuk "Kreatif & Profesional" — agensi, tim, dan jasa profesional
const KREATIF_PRO_SUB_TYPES: SubTypeItem[] = [
  { value: "Digital & Marketing Agency", emoji: "📈", label: "Digital Agency" },
  { value: "SEO & Digital Specialist", emoji: "🔍", label: "SEO & Digital" },
  { value: "Konsultan", emoji: "📊", label: "Konsultan" },
  { value: "Tutor & Life Coach", emoji: "🎓", label: "Tutor & Coach" },
  { value: "Public Speaker & Trainer", emoji: "🎤", label: "Speaker & Trainer" },
  { value: "Notaris & PPAT", emoji: "⚖️", label: "Notaris & PPAT" },
];

export const SUB_TYPES: Record<string, SubTypeItem[]> = {
  "Kuliner": [
    { value: "Restoran & Warung Makan", emoji: "🍛", label: "Restoran" },
    { value: "Kafe", emoji: "☕", label: "Kafe" },
    { value: "Bakery & Pastry", emoji: "🥐", label: "Bakery" },
    { value: "Catering", emoji: "🍱", label: "Catering" },
    { value: "Minuman & Bubble Tea", emoji: "🧋", label: "Minuman" },
    { value: "Makanan Rumahan & Frozen Food", emoji: "🍲", label: "Dapur Rumahan" },
    { value: "Frozen Food Homemade", emoji: "🧊", label: "Frozen Food" },
    { value: "Kuliner Kaki Lima & Angkringan", emoji: "🍢", label: "Kaki Lima" },
    { value: "Jajanan Pasar & Kuliner Tradisional", emoji: "🍘", label: "Jajanan Pasar" },
    { value: "Herbal & Jamu", emoji: "🌿", label: "Herbal & Jamu" },
  ],
  "Toko": [
    { value: "Fashion & Pakaian", emoji: "👗", label: "Fashion" },
    { value: "Elektronik", emoji: "📱", label: "Elektronik" },
    { value: "Kecantikan & Kosmetik", emoji: "💄", label: "Kosmetik & Skincare" },
    { value: "Produk Lokal Handmade", emoji: "🧺", label: "Handmade" },
    { value: "Toko Online", emoji: "🛒", label: "Toko Online" },
    { value: "Minimarket & Sembako", emoji: "🏪", label: "Minimarket & Sembako" },
    { value: "Perabot & Furnitur", emoji: "🪑", label: "Furnitur" },
    { value: "Otomotif & Sparepart", emoji: "🏎️", label: "Sparepart & Aksesoris" },
    { value: "Pertanian & Peternakan", emoji: "🌾", label: "Pertanian & Peternakan" },
  ],
  "Toko & UMKM": [
    { value: "Fashion & Pakaian", emoji: "👗", label: "Fashion" },
    { value: "Elektronik", emoji: "📱", label: "Elektronik" },
    { value: "Kecantikan & Kosmetik", emoji: "💄", label: "Kosmetik & Skincare" },
    { value: "Produk Lokal Handmade", emoji: "🧺", label: "Handmade" },
    { value: "Toko Online", emoji: "🛒", label: "Toko Online" },
    { value: "Minimarket & Sembako", emoji: "🏪", label: "Minimarket & Sembako" },
    { value: "Perabot & Furnitur", emoji: "🪑", label: "Furnitur" },
    { value: "Otomotif & Sparepart", emoji: "🏎️", label: "Sparepart & Aksesoris" },
    { value: "Pertanian & Peternakan", emoji: "🌾", label: "Pertanian & Peternakan" },
  ],
  "Layanan & Reservasi": [
    { value: "Rental Mobil & Kendaraan", emoji: "🚗", label: "Rental Mobil & Kendaraan" },
    { value: "Travel & Wisata", emoji: "✈️", label: "Travel & Wisata" },
    { value: "Hotel & Penginapan", emoji: "🏨", label: "Penginapan" },
    { value: "Makeup Artist (MUA)", emoji: "💄", label: "Makeup Artist (MUA)" },
    { value: "Salon & Kecantikan", emoji: "💇", label: "Salon & Spa" },
    { value: "Barbershop", emoji: "✂️", label: "Barbershop" },
    { value: "Klinik & Kesehatan", emoji: "🏥", label: "Klinik & Kesehatan" },
    { value: "Gym & Olahraga", emoji: "🏋️", label: "Gym & Olahraga" },
    { value: "Event & Wedding Organizer", emoji: "🎉", label: "Event Organizer" },
    { value: "Otomotif & Bengkel", emoji: "🔧", label: "Bengkel & Servis" },
    { value: "Laundry", emoji: "🧺", label: "Laundry" },
    { value: "Jasa Rumah & Kebersihan", emoji: "🧹", label: "Jasa Rumah & Bersih" },
    { value: "Pendidikan & Kursus", emoji: "📚", label: "Les & Kursus" },
    { value: "Biro Jasa & Perizinan", emoji: "📋", label: "Biro Jasa" },
  ],
  "Jasa & Booking": [
    { value: "Rental Mobil & Kendaraan", emoji: "🚗", label: "Rental Mobil & Kendaraan" },
    { value: "Travel & Wisata", emoji: "✈️", label: "Travel & Wisata" },
    { value: "Hotel & Penginapan", emoji: "🏨", label: "Penginapan" },
    { value: "Makeup Artist (MUA)", emoji: "💄", label: "Makeup Artist (MUA)" },
    { value: "Salon & Kecantikan", emoji: "💇", label: "Salon & Spa" },
    { value: "Barbershop", emoji: "✂️", label: "Barbershop" },
    { value: "Klinik & Kesehatan", emoji: "🏥", label: "Klinik & Kesehatan" },
    { value: "Gym & Olahraga", emoji: "🏋️", label: "Gym & Olahraga" },
    { value: "Event & Wedding Organizer", emoji: "🎉", label: "Event Organizer" },
    { value: "Otomotif & Bengkel", emoji: "🔧", label: "Bengkel & Servis" },
    { value: "Laundry", emoji: "🧺", label: "Laundry" },
    { value: "Jasa Rumah & Kebersihan", emoji: "🧹", label: "Jasa Rumah & Bersih" },
    { value: "Pendidikan & Kursus", emoji: "📚", label: "Les & Kursus" },
    { value: "Biro Jasa & Perizinan", emoji: "📋", label: "Biro Jasa" },
  ],
  // "Portofolio" — individual / personal brand
  "Portofolio": PORTOFOLIO_PERSONAL_SUB_TYPES,
  // Backward-compat aliases (data lama di database)
  "Portofolio & Kreator": PORTOFOLIO_PERSONAL_SUB_TYPES,
  "Kreatif & Profesional": KREATIF_PRO_SUB_TYPES,
  "Company Profile": [
    { value: "Properti & Real Estate", emoji: "🏠", label: "Properti" },
    { value: "Konstruksi & Kontraktor", emoji: "🏗️", label: "Konstruksi" },
    { value: "Manufaktur & Pabrik", emoji: "🏭", label: "Manufaktur" },
    { value: "Logistik & Ekspedisi", emoji: "🚚", label: "Logistik & Kargo" },
    { value: "Yayasan & Organisasi Nonprofit", emoji: "🤝", label: "Yayasan & Organisasi" },
    { value: "Institusi Pendidikan & Pesantren", emoji: "🏫", label: "Sekolah & Kampus" },
  ],
  "Company": [
    { value: "Properti & Real Estate", emoji: "🏠", label: "Properti" },
    { value: "Konstruksi & Kontraktor", emoji: "🏗️", label: "Konstruksi" },
    { value: "Manufaktur & Pabrik", emoji: "🏭", label: "Manufaktur" },
    { value: "Logistik & Ekspedisi", emoji: "🚚", label: "Logistik & Kargo" },
    { value: "Yayasan & Organisasi Nonprofit", emoji: "🤝", label: "Yayasan & Organisasi" },
    { value: "Institusi Pendidikan & Pesantren", emoji: "🏫", label: "Sekolah & Kampus" },
  ],
};

export const TEMPLATE_NAMES: Record<string, string> = {
  "TEMPLATE_KULINER01": "Vista Prime 🍜",
  "TEMPLATE_JASA02": "Elevate One 💼",
  "TEMPLATE_PRODUK03": "Forge Flow 🛍️",
  "TEMPLATE_ELEGANT": "Noir Prestige 👑",
  "TEMPLATE_NATURAL": "Bumi Lestari 🌿",
  "TEMPLATE_COLORFUL": "Pop Riot 🎨",
  "TEMPLATE_MINIMALIST": "White Space ⚡",
  "TEMPLATE_DYNAMIC": "AI Design ✨",
  "TEMPLATE_RETRO": "Neon Wave 🌆",
  "TEMPLATE_FUTURISTIC": "Cyber Core 🤖",
};

export const LOADING_CHECKLIST = [
  { label: "Menulis headline & hero", desc: "Membuat judul utama yang menarik perhatian" },
  { label: "Menyusun cerita bisnis", desc: "Menulis tentang brand dan nilai bisnis Anda" },
  { label: "Menulis keunggulan & layanan", desc: "Merinci kelebihan dan layanan yang ditawarkan" },
  { label: "Menyiapkan testimoni & FAQ", desc: "Mengumpulkan bukti sosial dan pertanyaan umum" },
  { label: "Menyusun katalog & galeri", desc: "Membuat daftar menu/layanan dan galeri foto" },
  { label: "Kurasi portofolio proyek", desc: "Menyusun karya terbaik dan pencapaian bisnis" },
  { label: "Optimasi SEO & finalisasi", desc: "Mengatur metadata dan call-to-action kontak" },
];

export const LOADING_STEPS_PERCENT = [15, 30, 46, 58, 70, 82, 92];

export const SECTION_STEP_MAP: Record<string, number> = {
  header: 0, hero: 0,
  about: 1,
  benefits: 2,
  testimonials: 3, faq: 3,
  menu: 4, catalog: 4, gallery: 4, works: 4,
  cta: 5, contact: 5, footer: 5, seo: 5,
};

export const WIREFRAME_STEPS = ["Tentang", "Keunggulan", "Kontak"] as const;

// Variants for name acknowledgement / confirmation
export const NAME_ACK_VARIANTS = [
  "Baik, nama telah dicatat.",
  "Nama berhasil disimpan.",
  "Oke, nama sudah tersimpan.",
  "Siap, nama tercatat.",
  "Nama Anda sudah masuk sistem.",
  "Baik, nama sudah terdaftar."
];

export const DESCRIPTION_PROMPT = "Ceritakan bisnis atau profil Anda secara singkat — cukup 1-2 kalimat. Misalnya: karya/jasa yang ditawarkan, keahlian Anda, atau untuk siapa. Tekan Enter untuk lanjut jika ingin skip.";
export const DESCRIPTION_SKIP_KEYWORD = "lewat";
export const DESCRIPTION_INFERENCE_HIGH = "Saya lihat Anda bergerak di bidang %s — %s. Langsung buat website-nya?";
export const DESCRIPTION_INFERENCE_MEDIUM = "Saya lihat bidang usaha Anda adalah %s. Bisa pilih yang lebih spesifik?";
export const DESCRIPTION_INFERENCE_NONE = "Baik, silakan pilih jenis bisnis Anda:";

export const NAME_CONFIRM_VARIANTS = [
  "Itu nama aslinya, atau masih nama sementara? Pilih 'Ya' untuk lanjut, atau 'Ganti' jika ingin diubah 😊",
  "Apakah itu nama sebenarnya? Klik 'Ya' untuk lanjut, atau 'Ganti' jika ingin memasukkan nama lain.",
  "Nama tersebut terdengar seperti percobaan — pastikan ini yang Anda mau. Klik 'Ya' untuk lanjut atau 'Ganti'."
];

// Mapping keyword -> suggested type/subtype
export const NAME_TYPE_HINTS: Record<string, { type?: string; subType?: string }> = {
  "kopi": { type: "Kuliner", subType: "Kafe" },
  "kafe": { type: "Kuliner", subType: "Kafe" },
  "cafe": { type: "Kuliner", subType: "Kafe" },
  "restoran": { type: "Kuliner", subType: "Restoran & Warung Makan" },
  "warung": { type: "Kuliner", subType: "Restoran & Warung Makan" },
  "bakery": { type: "Kuliner", subType: "Bakery & Pastry" },
  "roti": { type: "Kuliner", subType: "Bakery & Pastry" },
  "frozen": { type: "Kuliner", subType: "Frozen Food Homemade" },
  "frozen food": { type: "Kuliner", subType: "Frozen Food Homemade" },
  "nugget": { type: "Kuliner", subType: "Frozen Food Homemade" },
  "siomay": { type: "Kuliner", subType: "Frozen Food Homemade" },
  "dimsum": { type: "Kuliner", subType: "Frozen Food Homemade" },
  "empanada": { type: "Kuliner", subType: "Frozen Food Homemade" },
  "risol": { type: "Kuliner", subType: "Frozen Food Homemade" },
  "dapur": { type: "Kuliner", subType: "Makanan Rumahan & Frozen Food" },
  "masakan": { type: "Kuliner", subType: "Makanan Rumahan & Frozen Food" },
  "lauk": { type: "Kuliner", subType: "Makanan Rumahan & Frozen Food" },
  "meal prep": { type: "Kuliner", subType: "Makanan Rumahan & Frozen Food" },
  "nasi box": { type: "Kuliner", subType: "Makanan Rumahan & Frozen Food" },
  "angkringan": { type: "Kuliner", subType: "Kuliner Kaki Lima & Angkringan" },
  "kaki lima": { type: "Kuliner", subType: "Kuliner Kaki Lima & Angkringan" },
  "street food": { type: "Kuliner", subType: "Kuliner Kaki Lima & Angkringan" },
  "nasi kucing": { type: "Kuliner", subType: "Kuliner Kaki Lima & Angkringan" },
  "wedangan": { type: "Kuliner", subType: "Kuliner Kaki Lima & Angkringan" },
  "taichan": { type: "Kuliner", subType: "Kuliner Kaki Lima & Angkringan" },
  "seblak": { type: "Kuliner", subType: "Kuliner Kaki Lima & Angkringan" },
  "lesehan": { type: "Kuliner", subType: "Kuliner Kaki Lima & Angkringan" },
  "gerobak": { type: "Kuliner", subType: "Kuliner Kaki Lima & Angkringan" },
  "jajanan pasar": { type: "Kuliner", subType: "Jajanan Pasar & Kuliner Tradisional" },
  "pasaran": { type: "Kuliner", subType: "Jajanan Pasar & Kuliner Tradisional" },
  "kue basah": { type: "Kuliner", subType: "Jajanan Pasar & Kuliner Tradisional" },
  "pasar": { type: "Kuliner", subType: "Jajanan Pasar & Kuliner Tradisional" },
  "jenang": { type: "Kuliner", subType: "Jajanan Pasar & Kuliner Tradisional" },
  "lupis": { type: "Kuliner", subType: "Jajanan Pasar & Kuliner Tradisional" },
  "getuk": { type: "Kuliner", subType: "Jajanan Pasar & Kuliner Tradisional" },
  "lemper": { type: "Kuliner", subType: "Jajanan Pasar & Kuliner Tradisional" },
  "snack box": { type: "Kuliner", subType: "Jajanan Pasar & Kuliner Tradisional" },
  "jamu": { type: "Kuliner", subType: "Herbal & Jamu" },
  "herbal": { type: "Kuliner", subType: "Herbal & Jamu" },
  "madu": { type: "Kuliner", subType: "Herbal & Jamu" },
  "rental": { type: "Layanan & Reservasi", subType: "Rental Mobil & Kendaraan" },
  "sewa mobil": { type: "Layanan & Reservasi", subType: "Rental Mobil & Kendaraan" },
  "sewa motor": { type: "Layanan & Reservasi", subType: "Rental Mobil & Kendaraan" },
  "klinik": { type: "Layanan & Reservasi", subType: "Klinik & Kesehatan" },
  "dokter": { type: "Layanan & Reservasi", subType: "Klinik & Kesehatan" },
  "salon": { type: "Layanan & Reservasi", subType: "Salon & Kecantikan" },
  "barbershop": { type: "Layanan & Reservasi", subType: "Barbershop" },
  "travel": { type: "Layanan & Reservasi", subType: "Travel & Wisata" },
  "hotel": { type: "Layanan & Reservasi", subType: "Hotel & Penginapan" },
  "villa": { type: "Layanan & Reservasi", subType: "Hotel & Penginapan" },
  "penginapan": { type: "Layanan & Reservasi", subType: "Hotel & Penginapan" },
  "wisata": { type: "Layanan & Reservasi", subType: "Travel & Wisata" },
  "tour": { type: "Layanan & Reservasi", subType: "Travel & Wisata" },
  "toko": { type: "Toko", subType: "Toko Online" },
  "toko online": { type: "Toko", subType: "Toko Online" },
  "fashion": { type: "Toko", subType: "Fashion & Pakaian" },
  "skincare": { type: "Toko", subType: "Kecantikan & Kosmetik" },
  "kosmetik": { type: "Toko", subType: "Kecantikan & Kosmetik" },
  "parfum": { type: "Toko", subType: "Kecantikan & Kosmetik" },
  "sparepart": { type: "Toko", subType: "Otomotif & Sparepart" },
  "bengkel": { type: "Layanan & Reservasi", subType: "Otomotif & Bengkel" },
  "laundry": { type: "Layanan & Reservasi", subType: "Laundry" },
  "gym": { type: "Layanan & Reservasi", subType: "Gym & Olahraga" },
  "fitness": { type: "Layanan & Reservasi", subType: "Gym & Olahraga" },
  "cleaning": { type: "Layanan & Reservasi", subType: "Jasa Rumah & Kebersihan" },
  "cuci ac": { type: "Layanan & Reservasi", subType: "Jasa Rumah & Kebersihan" },
  // Portofolio — individual / personal brand
  "konsultan": { type: "Kreatif & Profesional", subType: "Konsultan" },
  "fotogra": { type: "Portofolio", subType: "Fotografer" },
  "minuman": { type: "Kuliner", subType: "Minuman & Bubble Tea" },
  "bubble": { type: "Kuliner", subType: "Minuman & Bubble Tea" },
  "kreator": { type: "Portofolio", subType: "Konten Kreator" },
  "creator": { type: "Portofolio", subType: "Konten Kreator" },
  "konten": { type: "Portofolio", subType: "Konten Kreator" },
  "influencer": { type: "Portofolio", subType: "Konten Kreator" },
  "youtuber": { type: "Portofolio", subType: "Konten Kreator" },
  "tiktoker": { type: "Portofolio", subType: "Konten Kreator" },
  "streamer": { type: "Portofolio", subType: "Konten Kreator" },
  "vlogger": { type: "Portofolio", subType: "Konten Kreator" },
  "video": { type: "Portofolio", subType: "Videografer" },
  "desain": { type: "Portofolio", subType: "Desainer" },
  "design": { type: "Portofolio", subType: "Desainer" },
  "ilustrator": { type: "Portofolio", subType: "Ilustrator & Seniman" },
  "illustrator": { type: "Portofolio", subType: "Ilustrator & Seniman" },
  "seniman": { type: "Portofolio", subType: "Ilustrator & Seniman" },
  "arsitek": { type: "Portofolio", subType: "Arsitek & Desainer Interior" },
  "interior": { type: "Portofolio", subType: "Arsitek & Desainer Interior" },
  "penulis": { type: "Portofolio", subType: "Penulis & Copywriter" },
  "copywriter": { type: "Portofolio", subType: "Penulis & Copywriter" },
  "developer": { type: "Portofolio", subType: "Developer & IT" },
  "software": { type: "Portofolio", subType: "Developer & IT" },
  "programmer": { type: "Portofolio", subType: "Developer & IT" },
  "engineer": { type: "Portofolio", subType: "Developer & IT" },
  "frontend": { type: "Portofolio", subType: "Developer & IT" },
  "backend": { type: "Portofolio", subType: "Developer & IT" },
  "fullstack": { type: "Portofolio", subType: "Developer & IT" },
  "website": { type: "Portofolio", subType: "Developer & IT" },
  "musik": { type: "Portofolio", subType: "Musisi & Entertainer" },
  "band": { type: "Portofolio", subType: "Musisi & Entertainer" },
  // Kreatif & Profesional — agency/tim/jasa
  "seo": { type: "Kreatif & Profesional", subType: "SEO & Digital Specialist" },
  "agency": { type: "Kreatif & Profesional", subType: "Digital & Marketing Agency" },
  "tutor": { type: "Kreatif & Profesional", subType: "Tutor & Life Coach" },
  "coach": { type: "Kreatif & Profesional", subType: "Tutor & Life Coach" },
  "speaker": { type: "Kreatif & Profesional", subType: "Public Speaker & Trainer" },
  "trainer": { type: "Kreatif & Profesional", subType: "Public Speaker & Trainer" },
  "wedding organizer": { type: "Layanan & Reservasi", subType: "Event & Wedding Organizer" },
  "wo ": { type: "Layanan & Reservasi", subType: "Event & Wedding Organizer" },
  "event organizer": { type: "Layanan & Reservasi", subType: "Event & Wedding Organizer" },
  "biro jasa": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "pbg": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "imb": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "simbg": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "stnk": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "bpkb": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "samsat": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "paspor": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "perizinan": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "perijinan": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "legalitas": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "nib": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "oss": { type: "Layanan & Reservasi", subType: "Biro Jasa & Perizinan" },
  "notaris": { type: "Kreatif & Profesional", subType: "Notaris & PPAT" },
  "ppat": { type: "Kreatif & Profesional", subType: "Notaris & PPAT" },
  "ajb": { type: "Kreatif & Profesional", subType: "Notaris & PPAT" },
  "akta": { type: "Kreatif & Profesional", subType: "Notaris & PPAT" },
  "pengacara": { type: "Kreatif & Profesional", subType: "Notaris & PPAT" },
  "advokat": { type: "Kreatif & Profesional", subType: "Notaris & PPAT" },
  "hukum": { type: "Kreatif & Profesional", subType: "Notaris & PPAT" },
  "properti": { type: "Company Profile", subType: "Properti & Real Estate" },
  "kontraktor": { type: "Company Profile", subType: "Konstruksi & Kontraktor" },
  "logistik": { type: "Company Profile", subType: "Logistik & Ekspedisi" },
  "ekspedisi": { type: "Company Profile", subType: "Logistik & Ekspedisi" },
  "sekolah": { type: "Company Profile", subType: "Institusi Pendidikan & Pesantren" },
  "pesantren": { type: "Company Profile", subType: "Institusi Pendidikan & Pesantren" },
  "yayasan": { type: "Company Profile", subType: "Yayasan & Organisasi Nonprofit" },
};
